version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Python versiyonu
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running tests...
      - python -m unittest discover  # Eğer testler varsa
      - echo Building the project...
      - python setup.py sdist bdist_wheel  # Eğer bir Python paketi oluşturuyorsanız
  post_build:
    commands:
      - echo Build completed.
      - aws s3 sync ./dist s3://my-deployment-bucket-for --delete  # Eğer dosyaları S3'e yükleyecekseniz
artifacts:
  files:
    - '**/*'
  discard-paths: yes
